# sample ninja makefile

build: targets.ninja
	ninja -v

build.ninja:
	render-template.py build.ninja srcdir=. bindir=. > $@

targets.ninja: targets.yaml
	render-template.py targets.ninja --srcdir=. --bindir=. targets.yaml > $@

clean:
	ninja -v -t clean

.PHONY: build clean build.ninja

# vim: ft=make
# EOF
